### ISSUE TITLE
Error not detected for my Reactjs Typescript project

### ISSUE THREAD

**Issue by MoMoWongHK** [EPMatt/reviewdog-action-tsc#38]
Hi,
I am trying to use this action for my React project while I can log the message using `tsc` on my computer but no error for this action

```
P:\myProject\src>tsc
Route/RouterManager/RouterManager.tsx:21:13 - error TS2339: Property 'location' does not exist on type '{ children?: ReactNode; }'.

21       props.location.pathname.split("/").length > 0 &&
               ~~~~~~~~

Route/RouterManager/RouterManager.tsx:22:13 - error TS2339: Property 'location' does not exist on type '{ children?: ReactNode; }'.

22       props.location.pathname.split("/")[1] !== ""
               ~~~~~~~~


Found 2 errors.
```

My .yml:

```
name: tsc
on:
  pull_request:
    branches:
      - master
      - main
jobs:
  tsc:
    name: runner / tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EPMatt/reviewdog-action-tsc@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_on_error: true
```

I am thinking whether it is related to my messing "workdir" ?
this is a very normal `npx create-react-app my-app --template typescript` website
