### ISSUE TITLE
`tsc_flags` option wrong default value

### ISSUE THREAD

**Issue by EPMatt** [EPMatt/reviewdog-action-tsc#39]
I think I encountered similar problems with @MoMoWongHK here a few days ago, but wasn't able to share it until now.
When I looked at the GitHub Actions output, it was like this, instead of real TypeScript errors.
![image](https://user-images.githubusercontent.com/63445490/152475258-49c921b2-fd1d-4ff2-87dc-a945d9de0374.png)
I struggled to find what could be the reason, and then found that at the line below, the tsc_flags are defaulted to '.' which would mean that `tsc .` is executed instead of `tsc` when tsc_flags is not set.
https://github.com/EPMatt/reviewdog-action-tsc/blob/fcd00d5f64b057f2a119879a45b3edcb5c8a83fa/script.sh#L30

I was able to solve that problem by explicitly setting tsc_flags to `' '` (it should have a whitespace or it will be ignored), however the results were not same as in the README.
![image](https://user-images.githubusercontent.com/63445490/152477220-d3de0407-68d1-42a0-b535-c70bcbb77b65.png)

_Originally posted by @jihoon416 in https://github.com/EPMatt/reviewdog-action-tsc/issues/38#issuecomment-1029646656_

**Comment by EPMatt** [comment]
Hi @jihoon416,

> I struggled to find what could be the reason, and then found that at the line below, the tsc_flags are defaulted to '.' which would mean that tsc . is executed instead of tsc when tsc_flags is not set.

Thanks for spotting the bug!  That's definitely a typo since the default value at line 30 should be set to `''`, as stated in the action docs. Would you mind submitting a PR for this? :)

> I was able to solve that problem by explicitly setting tsc_flags to ' ' (it should have a whitespace or it will be ignored), however the results were not same as in the README.

This might be an issue with the action config. Could you please share the YAML for the GitHub Actions workflow you're trying to setup?

Thanks!

**Comment by jihoon416** [comment]
Hello @EPMatt Thanks for creating a separete issue.
Yep I'll get on to submitting a PR!

Here's my full YAML file.
```yml
name: Checks

on: pull_request

jobs:
  ESLint:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v2

      - name: 🏗 Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: 📦 Install dependencies
        run: yarn

      - name: 🐶 Activate Review Dog
        uses: reviewdog/action-eslint@v1
        with:
          fail_on_error: true

  Typescript:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v2

      - name: 🏗 Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: 📦 Install dependencies
        run: yarn

      - name: 🐶 Activate Review Dog
        uses: EPMatt/reviewdog-action-tsc@v1
        with:
          tsc_flags: ' '
          fail_on_error: true

```
It performs two jobs, one for ESLint and one for tsc. ESLint is working fine, but for tsc the result was as below.
![tsc action Screenshot](https://user-images.githubusercontent.com/63445490/152477220-d3de0407-68d1-42a0-b535-c70bcbb77b65.png)
